services:
  web:
    build: .
    deploy:
      mode: replicated
      replicas: 2
  redis:
    image: redis
    volumes:
      - "./data:/data"
  nginx:
    image: nginx:latest
    volumes: 
      - $PWD:/etc/nginx:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
