services:
  web:
    build: .
  redis:
    image: redis
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes
  nginx:
    image: nginx:latest
    volumes: 
      - $PWD:/etc/nginx:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
